### ISSUE TITLE
broken links when url has trailing backslash

### ISSUE THREAD

**Issue by DZGoldman** [connext/documentation#13]
To repro:
- go to https://docs.connext.network/Integration/SystemOverview/faq
- it will become https://docs.connext.network/Integration/SystemOverview/faq/ (<- backslash)
- "How it works" in main content (not sidebar)

**Comment by rhlsthrm** [comment]
@DZGoldman I can't seem to reproduce anything with backslashes here. Would it be possible for you to film a Loom video or something?
