### ISSUE TITLE
Broken Link https://docs.connext.network/background/faq/

### ISSUE THREAD

**Issue by Dominik1999** [connext/documentation#2]
When I wanted to open `System Overview` on https://docs.connext.network/ I got

![Screenshot from 2021-09-20 13-14-40](https://user-images.githubusercontent.com/35031754/133994072-09f0de27-db8c-49e2-a42b-fb87dccda221.png)

**Comment by rhlsthrm** [comment]
<img width="1557" alt="Screen Shot 2021-09-20 at 15 22 17" src="https://user-images.githubusercontent.com/11512787/133994482-132fdb70-0d9a-4724-a3b6-d1304eb002d9.png">

It seems to work for me. Can you tell me exactly what links you tried to click?

**Comment by Dominik1999** [comment]
Hmm that is strange. The broken link (for me) is https://docs.connext.network/background/faq

**Comment by Dominik1999** [comment]
ok, it happens when I click "System Overview" her
![Screenshot from 2021-09-21 16-08-40](https://user-images.githubusercontent.com/35031754/134186441-796f88fb-9770-40fa-b0af-816a2f63f83c.png)
e

**Comment by rhlsthrm** [comment]
Fixed now!
